name: Docs Update Guard

on:
  workflow_call:

jobs:
  check-docs-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for diff)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine diff range
        id: range
        run: |
          AFTER="${GITHUB_SHA}"
          BEFORE="$(jq -r '.before' < "$GITHUB_EVENT_PATH")"

          # Cas des premiers commits (CREATE branch) : before = 0000...
          if [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            # Si c'est le tout premier commit, on skippe (pas de base pour comparer)
            if [ "$(git rev-list --count "$AFTER")" -eq 1 ]; then
              echo "skip=true" >> $GITHUB_OUTPUT
              exit 0
            else
              # Prendre le parent direct du commit courant
              BEFORE="$(git rev-parse "${AFTER}^")"
            fi
          fi

          echo "before=$BEFORE" >> $GITHUB_OUTPUT
          echo "after=$AFTER"  >> $GITHUB_OUTPUT

      - name: Skip early if no range
        if: steps.range.outputs.skip == 'true'
        run: echo "No previous commit to compare against; skipping."

      - name: Compute changed files
        id: changes
        if: steps.range.outputs.skip != 'true'
        run: |
          BEFORE="${{ steps.range.outputs.before }}"
          AFTER="${{ steps.range.outputs.after }}"

          git diff --name-only "$BEFORE" "$AFTER" > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

          # Flags de changement côté source
          if grep -qE '^apps/' changed_files.txt; then echo "apps_changed=1" >> $GITHUB_OUTPUT; else echo "apps_changed=0" >> $GITHUB_OUTPUT; fi
          if grep -qE '^infra/' changed_files.txt; then echo "infra_changed=1" >> $GITHUB_OUTPUT; else echo "infra_changed=0" >> $GITHUB_OUTPUT; fi
          if grep -qx 'version.txt' changed_files.txt; then echo "version_changed=1" >> $GITHUB_OUTPUT; else echo "version_changed=0" >> $GITHUB_OUTPUT; fi

          # Flags de modification des docs
          if grep -qx 'docs/apps.md' changed_files.txt;  then echo "docs_apps_changed=1"  >> $GITHUB_OUTPUT; else echo "docs_apps_changed=0"  >> $GITHUB_OUTPUT; fi
          if grep -qx 'docs/infra.md' changed_files.txt; then echo "docs_infra_changed=1" >> $GITHUB_OUTPUT; else echo "docs_infra_changed=0" >> $GITHUB_OUTPUT; fi
          if grep -qx 'docs/version.md' changed_files.txt; then echo "docs_version_changed=1" >> $GITHUB_OUTPUT; else echo "docs_version_changed=0" >> $GITHUB_OUTPUT; fi

      - name: Enforce docs updates
        if: steps.range.outputs.skip != 'true'
        run: |
          missing=0
          msgs=()

          apps_changed="${{ steps.changes.outputs.apps_changed }}"
          infra_changed="${{ steps.changes.outputs.infra_changed }}"
          version_changed="${{ steps.changes.outputs.version_changed }}"

          docs_apps_changed="${{ steps.changes.outputs.docs_apps_changed }}"
          docs_infra_changed="${{ steps.changes.outputs.docs_infra_changed }}"
          docs_version_changed="${{ steps.changes.outputs.docs_version_changed }}"

          # Règles d’exigence
          if [ "$apps_changed" = "1" ] && [ "$docs_apps_changed" = "0" ]; then
            msgs+=("Documentation non mise à jour: 'docs/apps.md' n'a pas été modifié alors que 'apps/**' a changé.")
            missing=1
          fi

          if [ "$infra_changed" = "1" ] && [ "$docs_infra_changed" = "0" ]; then
            msgs+=("Documentation non mise à jour: 'docs/infra.md' n'a pas été modifié alors que 'infra/**' a changé.")
            missing=1
          fi

          if [ "$version_changed" = "1" ] && [ "$docs_version_changed" = "0" ]; then
            msgs+=("Documentation non mise à jour: 'docs/version.md' n'a pas été modifié alors que 'version.txt' a changé.")
            missing=1
          fi

          if [ $missing -eq 1 ]; then
            echo "❌ Échec : la documentation liée aux changements n'a pas été mise à jour."
            printf '%s\n' "${msgs[@]}"
            exit 1
          else
            echo "✅ OK : documentation mise à jour (ou aucun changement nécessitant une MAJ)."
          fi

